/** Coding & token plan guide — pricing snapshot July 2026. Confirm on official sites. */
window.PLANS = [
  {
    id: "mimo",
    name: "Xiaomi MiMo Token Plan",
    vendor: "Xiaomi MiMo",
    tagline: "Flagship MiMo-V2.5 models for coding agents, with transparent credit quotas.",
    startingPrice: 6,
    currency: "USD",
    priceLabel: "from $6/mo",
    badge: "Value",
    category: ["token", "china", "multimodal"],
    quotaStyle: "Monthly credits",
    tools: ["OpenCode", "OpenClaw", "Codex", "Claude Code"],
    models: ["mimo-v2.5-pro", "mimo-v2.5", "mimo-v2.5-asr", "mimo-v2.5-tts"],
    highlights: [
      "Four tiers from Lite to Max",
      "Night rate 0.8× (UTC 16:00–24:00)",
      "Annual plans at ~12% off",
      "TTS free for a limited time",
    ],
    url: "https://mimo.mi.com/token-plan",
    docsUrl: "https://mimo.mi.com/docs/en-US/price/token-plan",
    color: "#FF6900",
    tiers: [
      {
        name: "Lite",
        price: "$6",
        period: "/mo",
        alt: "¥39/mo",
        quota: "4.1B credits",
        note: "~200 medium tasks / mo (mimo-v2.5)",
      },
      {
        name: "Standard",
        price: "$16",
        period: "/mo",
        alt: "¥99/mo",
        quota: "11B credits",
        note: "~1,600 medium tasks / mo",
        popular: true,
      },
      {
        name: "Pro",
        price: "$50",
        period: "/mo",
        alt: "¥329/mo",
        quota: "38B credits",
        note: "~5,600 medium tasks / mo",
      },
      {
        name: "Max",
        price: "$100",
        period: "/mo",
        alt: "¥659/mo",
        quota: "82B credits",
        note: "~12,800 medium tasks / mo",
      },
    ],
  },
  {
    id: "minimax",
    name: "MiniMax Token Plan",
    vendor: "MiniMax",
    tagline: "Shared multimodal quota for coding agents, image, speech, and music.",
    startingPrice: 20,
    currency: "USD",
    priceLabel: "from $20/mo",
    badge: "Multimodal",
    category: ["token", "china", "multimodal"],
    quotaStyle: "5h + weekly windows",
    tools: ["MiniMax Code", "OpenClaw", "Claude Code", "Cline", "OpenAI-compatible"],
    models: ["MiniMax M3", "MiniMax M2.7", "M2.5", "Hailuo", "Speech", "Music"],
    highlights: [
      "All platform models in one quota",
      "Overflow via prepaid credits",
      "Team seat subscriptions available",
      "Yearly option: 2 months free",
    ],
    url: "https://platform.minimax.io/subscribe/token-plan",
    docsUrl: "https://platform.minimax.io/docs/guides/pricing-token-plan",
    color: "#E11D48",
    tiers: [
      {
        name: "Plus",
        price: "$20",
        period: "/mo",
        quota: "5h + weekly windows",
        note: "~3–4 concurrent agents",
      },
      {
        name: "Max",
        price: "$50",
        period: "/mo",
        quota: "5h + weekly windows",
        note: "~4–5 agents, daily coding",
        popular: true,
      },
      {
        name: "Ultra",
        price: "$120",
        period: "/mo",
        quota: "5h + weekly windows",
        note: "~6–7 agents, heavy sessions",
      },
    ],
  },
  {
    id: "opencode-go",
    name: "OpenCode Go",
    vendor: "OpenCode / Anomaly",
    tagline: "Curated open coding models with generous dollar-based usage windows.",
    startingPrice: 5,
    currency: "USD",
    priceLabel: "$5 then $10/mo",
    badge: "Best entry",
    category: ["aggregator", "global", "open"],
    quotaStyle: "$12 / 5h · $30 / week · $60 / mo",
    tools: ["OpenCode", "Any Anthropic/OpenAI agent"],
    models: [
      "Grok 4.5",
      "GLM-5.2",
      "Kimi K3",
      "MiMo-V2.5",
      "MiniMax M3",
      "Qwen3.7",
      "DeepSeek V4",
      "Hy3",
    ],
    highlights: [
      "$5 first month, then $10/mo",
      "16+ curated open models",
      "Hosted US / EU / Singapore",
      "Top up via Zen balance",
    ],
    url: "https://opencode.ai/go",
    docsUrl: "https://opencode.ai/docs/go/",
    color: "#F59E0B",
    tiers: [
      {
        name: "Go",
        price: "$10",
        period: "/mo",
        alt: "$5 first month",
        quota: "$60 monthly usage value",
        note: "Request counts vary by model cost",
        popular: true,
      },
    ],
  },
  {
    id: "glm",
    name: "GLM Coding Plan",
    vendor: "Zhipu · Z.ai",
    tagline: "GLM-5.2 class models with bundled vision, search, and repo MCPs.",
    startingPrice: 18,
    currency: "USD",
    priceLabel: "from $18/mo",
    badge: "MCP packed",
    category: ["token", "china", "mcp"],
    quotaStyle: "5h + weekly prompts",
    tools: ["Claude Code", "Cline", "OpenCode", "20+ clients"],
    models: ["GLM-5.2", "GLM-5-Turbo", "GLM-4.7"],
    highlights: [
      "Vision, Web Search, Web Reader, Zread MCPs",
      "Peak-hour multipliers for advanced models",
      "~15–30× API value vs fee",
      "Strong agentic coding benchmarks",
    ],
    url: "https://z.ai/subscribe",
    docsUrl: "https://docs.z.ai/devpack/overview",
    color: "#2563EB",
    tiers: [
      {
        name: "Lite",
        price: "$18",
        period: "/mo",
        quota: "~80 prompts / 5h · ~400 / week",
        note: "100 MCP calls / mo",
      },
      {
        name: "Pro",
        price: "$72",
        period: "/mo",
        quota: "~400 prompts / 5h · ~2,000 / week",
        note: "1,000 MCP calls · 5× Lite",
        popular: true,
      },
      {
        name: "Max",
        price: "$160",
        period: "/mo",
        quota: "~1,600 prompts / 5h · ~8,000 / week",
        note: "4,000 MCP calls · 20× Lite",
      },
    ],
  },
  {
    id: "kimi",
    name: "Kimi Code",
    vendor: "Moonshot · Kimi",
    tagline: "Long-context coding inside Kimi membership, with HighSpeed option.",
    startingPrice: 19,
    currency: "USD",
    priceLabel: "from $19/mo",
    badge: "Long context",
    category: ["token", "china", "membership"],
    quotaStyle: "Shared credits + Code 5h/week limits",
    tools: ["Kimi Code CLI", "Claude Code", "Roo Code", "Cursor"],
    models: ["Kimi for Coding", "Kimi for Coding HighSpeed", "K3"],
    highlights: [
      "Up to ~100 tok/s generation",
      "HighSpeed ~5–6× faster (Allegretto+)",
      "Shared credit pool with Agent features",
      "Annual billing saves up to $480/yr",
    ],
    url: "https://www.kimi.com/code",
    docsUrl: "https://www.kimi.com/help/kimi-code/membership-guide",
    color: "#BE185D",
    tiers: [
      {
        name: "Moderato",
        price: "$19",
        period: "/mo",
        alt: "$15/mo annual",
        quota: "1× Kimi Code credits",
        note: "Entry paid tier",
      },
      {
        name: "Allegretto",
        price: "$39",
        period: "/mo",
        alt: "$31/mo annual",
        quota: "5× Code · HighSpeed unlock",
        note: "Kimi Claw included",
        popular: true,
      },
      {
        name: "Allegro",
        price: "$99",
        period: "/mo",
        alt: "$79/mo annual",
        quota: "15× Kimi Code credits",
        note: "4 concurrent agent tasks",
      },
      {
        name: "Vivace",
        price: "$199",
        period: "/mo",
        alt: "$159/mo annual",
        quota: "30× Kimi Code credits",
        note: "Flagship capacity",
      },
    ],
  },
  {
    id: "stepfun",
    name: "StepFun Step Plan",
    vendor: "StepFun",
    tagline: "Credit-based monthly allowance for Step flagship models and routing.",
    startingPrice: 6.99,
    currency: "USD",
    priceLabel: "from $6.99/mo",
    badge: "Flexible",
    category: ["token", "china", "multimodal"],
    quotaStyle: "Monthly credits (no 5h window)",
    tools: ["OpenClaw", "Claude Code", "Trae", "Cursor", "Cline", "OpenCode"],
    models: ["step-3.7-flash", "step-3.5-flash", "stepaudio", "step-router", "step-image-edit"],
    highlights: [
      "Spend credits anytime in the month",
      "Booster packs when you run out",
      "~$1 ≈ 7M credits",
      "Same speed across all tiers",
    ],
    url: "https://platform.stepfun.ai/step-plan",
    docsUrl: "https://platform.stepfun.ai/docs/en/step-plan/overview",
    color: "#0891B2",
    tiers: [
      {
        name: "Flash Mini",
        price: "$6.99",
        period: "/mo",
        alt: "$69.99/yr",
        quota: "400M credits / mo",
        note: "Getting started",
      },
      {
        name: "Flash Plus",
        price: "$9.99",
        period: "/mo",
        alt: "$95.99/yr",
        quota: "1,600M credits / mo",
        note: "Daily productivity",
        popular: true,
      },
      {
        name: "Flash Pro",
        price: "$29",
        period: "/mo",
        alt: "$289/yr",
        quota: "8,000M credits / mo",
        note: "Heavy AI use",
      },
      {
        name: "Flash Max",
        price: "$99",
        period: "/mo",
        alt: "$989/yr",
        quota: "40,000M credits / mo",
        note: "Professional workloads",
      },
    ],
  },
  {
    id: "qwen",
    name: "Qwen Cloud Token Plan",
    vendor: "Alibaba · Qwen Cloud",
    tagline: "Individual & Team credit subscriptions for Qwen and peer models across text, vision, speech, and image.",
    startingPrice: 6,
    currency: "USD",
    priceLabel: "from $6/mo",
    badge: "Multi-model",
    category: ["token", "global", "aggregator"],
    quotaStyle: "Credits · 5h + 7-day windows",
    tools: ["OpenAI / Anthropic compatible tools", "Harness tools"],
    models: [
      "Qwen3.8-Max-Preview",
      "qwen3.7-max",
      "glm-5.2",
      "deepseek-v4-pro",
      "wan2.7-image-pro",
    ],
    highlights: [
      "Individual Lite / Standard / Pro + Team seats",
      "Standard = 4× Lite credits · Pro = 16× Lite",
      "Limited-time promo pricing · confirm live",
      "Text, vision, speech, and image in one plan",
    ],
    url: "https://www.qwencloud.com/pricing/token-plan",
    docsUrl: "https://docs.qwencloud.com/token-plan/personal/token-plan-personal-overview",
    color: "#0F766E",
    tiers: [
      {
        name: "Lite",
        price: "$6",
        period: "/mo",
        alt: "List $8/mo",
        quota: "700 credits / 5h · 2,500 / 7 days",
        note: "1–2 concurrent agents",
      },
      {
        name: "Standard",
        price: "$18",
        period: "/mo",
        alt: "List $25/mo",
        quota: "3,000 credits / 5h · 10,000 / 7 days",
        note: "3–4 agents · 4× Lite",
        popular: true,
      },
      {
        name: "Pro",
        price: "$68",
        period: "/mo",
        alt: "List $80/mo",
        quota: "12,000 credits / 5h · 40,000 / 7 days",
        note: "6–8 agents · 16× Lite",
      },
      {
        name: "Team Standard",
        price: "$20",
        period: "/seat/mo",
        alt: "List $30/seat",
        quota: "25,000 credits / seat / mo",
        note: "Team admin + per-member keys",
      },
      {
        name: "Team Pro",
        price: "$75",
        period: "/seat/mo",
        alt: "List $100/seat",
        quota: "100,000 credits / seat / mo",
        note: "Frequent coding seats",
      },
      {
        name: "Team Max",
        price: "$200",
        period: "/seat/mo",
        quota: "250,000 credits / seat / mo",
        note: "Heavy core-dev seats",
      },
    ],
  },
  {
    id: "claude",
    name: "Claude Code / Claude Pro",
    vendor: "Anthropic",
    tagline: "The reference agentic coding experience on Claude Sonnet and Opus.",
    startingPrice: 20,
    currency: "USD",
    priceLabel: "from $20/mo",
    badge: "Gold standard",
    category: ["official", "global", "agent"],
    quotaStyle: "Usage windows by tier",
    tools: ["Claude Code CLI", "claude.ai", "Desktop"],
    models: ["Claude Sonnet", "Claude Opus"],
    highlights: [
      "Industry benchmark for agent quality",
      "Pro for daily use, Max for power users",
      "Native Anthropic tooling",
      "Higher cost, highest polish",
    ],
    url: "https://claude.ai/pricing",
    docsUrl: "https://docs.anthropic.com/en/docs/claude-code",
    color: "#D97706",
    tiers: [
      {
        name: "Pro",
        price: "$20",
        period: "/mo",
        quota: "Standard Claude usage",
        note: "Daily coding & Claude Code",
        popular: true,
      },
      {
        name: "Max 5×",
        price: "$100",
        period: "/mo",
        quota: "5× Pro capacity",
        note: "Heavy agent sessions",
      },
      {
        name: "Max 20×",
        price: "$200",
        period: "/mo",
        quota: "20× Pro capacity",
        note: "Team / extreme workloads",
      },
    ],
  },
  {
    id: "cursor",
    name: "Cursor",
    vendor: "Anysphere",
    tagline: "AI-native IDE with included model usage and agent features.",
    startingPrice: 20,
    currency: "USD",
    priceLabel: "from $20/mo",
    badge: "IDE",
    category: ["ide", "global", "agent"],
    quotaStyle: "Fast + slow request pools",
    tools: ["Cursor IDE"],
    models: ["Composer", "Claude", "GPT", "Gemini", "Custom keys"],
    highlights: [
      "Full IDE experience, not just API",
      "Agent mode and tab completion",
      "Bring your own keys for extras",
      "Different product class vs token packs",
    ],
    url: "https://cursor.com/pricing",
    docsUrl: "https://docs.cursor.com",
    color: "#0EA5E9",
    tiers: [
      {
        name: "Pro",
        price: "$20",
        period: "/mo",
        quota: "Included frontier usage",
        note: "Individual developers",
        popular: true,
      },
      {
        name: "Pro+",
        price: "$60",
        period: "/mo",
        quota: "Expanded usage",
        note: "Heavier agent work",
      },
      {
        name: "Ultra",
        price: "$200",
        period: "/mo",
        quota: "Maximum included usage",
        note: "Power users",
      },
    ],
  },
  {
    id: "google",
    name: "Google AI Plans",
    vendor: "Google",
    tagline: "Gemini + Google Antigravity coding platform with compute-based usage windows.",
    startingPrice: 8,
    currency: "USD",
    priceLabel: "from $7.99/mo",
    badge: "Antigravity",
    category: ["official", "global", "agent"],
    quotaStyle: "Compute limits · ~5h refresh",
    tools: ["Gemini app", "Google Antigravity", "Google One"],
    models: ["Gemini 3.5 Flash", "Gemini family", "Gemini Spark (Ultra)"],
    highlights: [
      "Plus / Pro / Ultra tiers for different intensity",
      "Ultra aimed at developers & Antigravity priority",
      "Pay-as-you-go top-up credits available",
      "Storage + YouTube Premium on higher Ultra",
    ],
    url: "https://one.google.com/ai",
    docsUrl: "https://blog.google/products-and-platforms/products/google-one/google-ai-subscriptions/",
    color: "#4285F4",
    tiers: [
      {
        name: "AI Plus",
        price: "$7.99",
        period: "/mo",
        quota: "Entry Gemini usage",
        note: "Light everyday AI",
      },
      {
        name: "AI Pro",
        price: "$19.99",
        period: "/mo",
        quota: "Standard compute limits",
        note: "5 TB Google One storage",
        popular: true,
      },
      {
        name: "AI Ultra",
        price: "$99.99",
        period: "/mo",
        quota: "~5× Pro in Gemini & Antigravity",
        note: "20 TB · YouTube Premium",
      },
      {
        name: "AI Ultra Max",
        price: "$199.99",
        period: "/mo",
        quota: "~20× Pro usage",
        note: "Highest Ultra · Genie / Mariner extras",
      },
    ],
  },
  {
    id: "openai",
    name: "OpenAI ChatGPT / Codex",
    vendor: "OpenAI",
    tagline: "ChatGPT plans with bundled Codex for local, cloud, and code-review agent work.",
    startingPrice: 8,
    currency: "USD",
    priceLabel: "from $8/mo",
    badge: "Codex",
    category: ["official", "global", "agent"],
    quotaStyle: "5h windows · credits top-up",
    tools: ["ChatGPT", "Codex CLI", "IDE extension", "Codex web / iOS"],
    models: ["GPT-5.6 Sol / Terra / Luna", "GPT-5.3-Codex-Spark", "Codex agents"],
    highlights: [
      "Codex included across paid ChatGPT tiers",
      "Plus for daily coding; Pro 5× / 20× for heavy use",
      "Credits available when you hit limits",
      "Business / Enterprise for teams",
    ],
    url: "https://chatgpt.com/pricing/",
    docsUrl: "https://chatgpt.com/codex/pricing/",
    color: "#10A37F",
    tiers: [
      {
        name: "Go",
        price: "$8",
        period: "/mo",
        quota: "Limited Codex",
        note: "Lightweight entry",
      },
      {
        name: "Plus",
        price: "$20",
        period: "/mo",
        quota: "Expanded Codex · ~10–60 cloud tasks / 5h",
        note: "Most individual developers",
        popular: true,
      },
      {
        name: "Pro 5×",
        price: "$100",
        period: "/mo",
        quota: "5× Plus Codex usage",
        note: "Spark preview access",
      },
      {
        name: "Pro 20×",
        price: "$200",
        period: "/mo",
        quota: "20× Plus · maximum Codex",
        note: "Heaviest consumer tier",
      },
    ],
  },
  {
    id: "xai",
    name: "xAI SuperGrok",
    vendor: "xAI · Grok",
    tagline: "Standalone Grok subscriptions with higher limits, Imagine, voice, and multi-agent reasoning.",
    startingPrice: 10,
    currency: "USD",
    priceLabel: "from $10/mo",
    badge: "Grok",
    category: ["official", "global", "agent"],
    quotaStyle: "Weekly usage allowance by tier",
    tools: ["grok.com", "Grok iOS / Android", "X app (via Premium)", "xAI API (separate)"],
    models: ["Grok 4.5", "Grok 4 / Heavy", "Grok Imagine"],
    highlights: [
      "Lite → SuperGrok → Heavy standalone path",
      "Code gen, DeepSearch, voice, image & video",
      "Heavy unlocks multi-agent / Grok Heavy class",
      "Also bundled via X Premium / Premium+ (different product)",
    ],
    url: "https://x.ai/grok",
    docsUrl: "https://x.ai/pricing",
    color: "#111111",
    tiers: [
      {
        name: "SuperGrok Lite",
        price: "$10",
        period: "/mo",
        quota: "Entry paid standalone",
        note: "Light daily Grok + basic Imagine",
      },
      {
        name: "SuperGrok",
        price: "$30",
        period: "/mo",
        alt: "$300/yr",
        quota: "Higher limits · frontier Grok access",
        note: "Most common paid SuperGrok tier",
        popular: true,
      },
      {
        name: "SuperGrok Heavy",
        price: "$300",
        period: "/mo",
        alt: "Promo often ~$99 early months",
        quota: "Maximum limits · multi-agent / Heavy",
        note: "Research & heavy reasoning workloads",
      },
      {
        name: "X Premium+",
        price: "$40",
        period: "/mo",
        quota: "Grok via X bundle",
        note: "Social + Grok · not pure SuperGrok",
      },
    ],
  },
  {
    id: "longcat",
    name: "Meituan LongCat",
    vendor: "Meituan · LongCat",
    tagline: "LongCat-2.0 for agentic coding via pay-as-you-go API and flash-sale Token Packs.",
    startingPrice: 0.3,
    currency: "USD",
    priceLabel: "from ~$0.30/1M in",
    railUnit: "/1M in",
    badge: "Free cache",
    category: ["token", "china", "open"],
    quotaStyle: "PAYG or 30-day Token Packs",
    tools: ["OpenAI-compatible", "Anthropic-compatible", "Coding agents"],
    models: ["LongCat-2.0"],
    highlights: [
      "Cache hits free on Token Packs (uncached in/out only)",
      "Token Packs: flash sales 4× daily (BJT)",
      "Promo vs standard API rates; confirm live",
      "1M context · strong agentic coding focus",
    ],
    url: "https://longcat.chat/",
    docsUrl: "https://longcat.chat/platform/docs/zh/token-pack",
    color: "#FF6A00",
    tiers: [
      {
        name: "PAYG (promo)",
        price: "~$0.30",
        period: "/1M in",
        alt: "~$1.20 /1M out",
        quota: "Balance top-up · no monthly lock-in",
        note: "Limited-time launch rates · confirm live",
        popular: true,
      },
      {
        name: "PAYG (standard)",
        price: "~$0.75",
        period: "/1M in",
        alt: "~$2.95 /1M out",
        quota: "Balance top-up",
        note: "Planning rate if promo ends",
      },
      {
        name: "Token Pack",
        price: "Limited",
        period: "",
        alt: "30-day flash packs",
        quota: "Fixed token allotment",
        note: "BJT 10:00 / 16:00 / 21:00 / 23:00 · first come",
      },
    ],
  },
  {
    id: "modelark",
    name: "Volcengine Ark Coding Plan",
    vendor: "ByteDance · 火山引擎方舟",
    tagline: "China ModelArk coding subscription with Doubao and peer models, Auto mode, and shared tool quotas.",
    startingPrice: 5.5,
    currency: "USD",
    priceLabel: "from ¥40/mo",
    badge: "Multi-model",
    category: ["token", "china", "aggregator"],
    quotaStyle: "5h + weekly + monthly requests",
    tools: ["Claude Code", "Cursor", "Cline", "OpenCode", "OpenClaw", "Trae"],
    models: ["Doubao-Seed-Code", "DeepSeek", "GLM", "Kimi", "MiniMax", "Auto mode"],
    highlights: [
      "Lite & Pro (Pro ≈ 5× Lite quota)",
      "Official activity page for live promos",
      "Interactive coding tools only · not backend API",
      "International twin: BytePlus Coding Plan",
    ],
    url: "https://www.volcengine.com/activity/codingplan",
    docsUrl: "https://www.volcengine.com/product/ark",
    color: "#1664FF",
    tiers: [
      {
        name: "Lite",
        price: "¥40",
        period: "/mo",
        alt: "~$5.50 · promo often ~¥8.9–¥9.9",
        quota: "~1,200 / 5h · ~9,000 / week · ~18,000 / mo",
        note: "Medium-intensity coding",
        popular: true,
      },
      {
        name: "Pro",
        price: "¥200",
        period: "/mo",
        alt: "~$28 · promo often ~¥49.9",
        quota: "~6,000 / 5h · ~45,000 / week · ~90,000 / mo",
        note: "Heavy daily agent use · 5× Lite",
      },
    ],
  },
  {
    id: "byteplus",
    name: "BytePlus Coding Plan",
    vendor: "ByteDance · BytePlus ModelArk",
    tagline: "International ModelArk coding subscription — multi-model access for Claude Code, Cursor, and peers.",
    startingPrice: 10,
    currency: "USD",
    priceLabel: "from $10/mo",
    badge: "Multi-model",
    category: ["token", "global", "aggregator"],
    quotaStyle: "Subscription quota by tier",
    tools: ["Claude Code", "Cursor", "Cline", "Codex CLI", "Roo Code", "OpenCode", "OpenClaw", "TRAE"],
    models: [
      "Bytedance-Seed-Code",
      "GLM",
      "DeepSeek",
      "Kimi",
      "GPT-OSS",
      "Auto mode",
    ],
    highlights: [
      "Global / international BytePlus path (vs China Volcengine)",
      "Lite positioned ~3× Claude Pro usage class",
      "Pro = 5× Lite · ArkClaw perk on Pro (confirm live)",
      "Team Edition available for orgs",
    ],
    url: "https://www.byteplus.com/en/activity/codingplan",
    docsUrl: "https://docs.byteplus.com/en/docs/ModelArk/1925114",
    color: "#3B82F6",
    tiers: [
      {
        name: "Lite",
        price: "$10",
        period: "/mo",
        quota: "~3× Claude Pro usage class",
        note: "Flexible model pick or Auto mode",
        popular: true,
      },
      {
        name: "Pro",
        price: "$50",
        period: "/mo",
        quota: "5× Lite capacity",
        note: "Large-scale coding · ArkClaw perk",
      },
    ],
  },
  {
    id: "sakana",
    name: "Sakana Fugu Plan",
    vendor: "Sakana AI",
    tagline: "Multi-agent orchestration as a model — Fugu & Fugu Ultra on subscription or PAYG.",
    startingPrice: 20,
    currency: "USD",
    priceLabel: "from $20/mo",
    badge: "Multi-agent",
    category: ["token", "global", "agent"],
    quotaStyle: "Monthly allowance or PAYG tokens",
    tools: ["Sakana Console API", "Agent workflows"],
    models: ["Fugu", "Fugu Ultra", "Fugu Cyber (PAYG)"],
    highlights: [
      "Every subscription tier includes Fugu + Fugu Ultra",
      "Pro = 10× Standard · Max = 20× Standard",
      "PAYG Ultra: $5 in / $30 out per 1M (higher >272K)",
      "Orchestration tokens count toward usage",
    ],
    url: "https://sakana.ai/fugu/",
    docsUrl: "https://console.sakana.ai/pricing",
    color: "#0D9488",
    tiers: [
      {
        name: "Standard",
        price: "$20",
        period: "/mo",
        quota: "Baseline allowance",
        note: "Light daily / experiments",
      },
      {
        name: "Pro",
        price: "$100",
        period: "/mo",
        quota: "10× Standard usage",
        note: "Regular coding & research sessions",
        popular: true,
      },
      {
        name: "Max",
        price: "$200",
        period: "/mo",
        quota: "20× Standard usage",
        note: "Heavy long-running workloads",
      },
    ],
  },
  {
    id: "bailian",
    name: "Alibaba Bailian Coding Plan",
    vendor: "Alibaba Cloud · Model Studio",
    tagline: "China Model Studio coding subscription with Qwen, Kimi, GLM, and MiniMax in one quota.",
    startingPrice: 28,
    currency: "USD",
    priceLabel: "from ¥200/mo",
    badge: "Multi-model",
    category: ["token", "china", "aggregator"],
    quotaStyle: "5h + weekly + monthly requests",
    tools: ["Claude Code", "Cursor", "Cline", "Qwen Code", "OpenClaw"],
    models: ["qwen3.7-plus", "qwen3.6-plus", "kimi-k2.5", "glm-5", "MiniMax-M2.5"],
    highlights: [
      "Pro is the current new-purchase tier (Lite discontinued)",
      "Up to ~90k requests / month",
      "Daily limited stock releases (often 09:30 BJT)",
      "Interactive coding only · not for backend automation",
    ],
    url: "https://www.aliyun.com/benefit/scene/codingplan",
    docsUrl: "https://help.aliyun.com/zh/model-studio/coding-plan",
    color: "#FF8A00",
    tiers: [
      {
        name: "Pro",
        price: "¥200",
        period: "/mo",
        alt: "~$28",
        quota: "6,000 / 5h · 45,000 / week · 90,000 / mo",
        note: "Lite stopped new purchase (Mar 2026)",
        popular: true,
      },
    ],
  },
  {
    id: "copilot",
    name: "GitHub Copilot",
    vendor: "GitHub · Microsoft",
    tagline: "Widely adopted IDE assistant with completions, chat, and agent features across editors.",
    startingPrice: 10,
    currency: "USD",
    priceLabel: "from $10/mo",
    badge: "IDE",
    category: ["ide", "global", "agent"],
    quotaStyle: "Premium requests by tier",
    tools: ["VS Code", "JetBrains", "Vim", "GitHub.com", "CLI"],
    models: ["GPT", "Claude", "Auto model routing"],
    highlights: [
      "Cheapest mainstream paid IDE assistant entry",
      "Deep GitHub PR / repo integration",
      "Pro+ unlocks more premium model access",
      "Business / Enterprise for orgs",
    ],
    url: "https://github.com/features/copilot",
    docsUrl: "https://docs.github.com/en/copilot",
    color: "#238636",
    tiers: [
      {
        name: "Pro",
        price: "$10",
        period: "/mo",
        quota: "Included premium requests",
        note: "Individual developers",
        popular: true,
      },
      {
        name: "Pro+",
        price: "$39",
        period: "/mo",
        quota: "Higher premium allowance",
        note: "More model choice & agent use",
      },
      {
        name: "Business",
        price: "$19",
        period: "/user/mo",
        quota: "Org controls",
        note: "Teams on GitHub",
      },
    ],
  },
  {
    id: "windsurf",
    name: "Windsurf",
    vendor: "Windsurf (Codeium)",
    tagline: "AI-native IDE with Cascade agent workflows and daily/weekly usage quotas.",
    startingPrice: 20,
    currency: "USD",
    priceLabel: "from $20/mo",
    badge: "IDE",
    category: ["ide", "global", "agent"],
    quotaStyle: "Daily / weekly quotas",
    tools: ["Windsurf IDE", "VS Code workflows"],
    models: ["Claude", "GPT", "Gemini", "Cascade agent"],
    highlights: [
      "Cascade auto-indexes large codebases",
      "Pro for daily work · Max for power users",
      "Team seats available",
      "Competes directly with Cursor-class IDEs",
    ],
    url: "https://windsurf.com/pricing",
    docsUrl: "https://docs.windsurf.com",
    color: "#0891B2",
    tiers: [
      {
        name: "Pro",
        price: "$20",
        period: "/mo",
        quota: "Pro daily/weekly quotas",
        note: "Individual developers",
        popular: true,
      },
      {
        name: "Max",
        price: "$200",
        period: "/mo",
        quota: "Highest individual quotas",
        note: "Heavy agent sessions",
      },
      {
        name: "Teams",
        price: "$40",
        period: "/seat/mo",
        quota: "Shared team tier",
        note: "Org workflows",
      },
    ],
  },
  {
    id: "kilo",
    name: "Kilo Pass",
    vendor: "Kilo.ai",
    tagline: "Monthly AI credit subscription with bonus credits and 500+ models across Kilo products.",
    startingPrice: 19,
    currency: "USD",
    priceLabel: "from $19/mo",
    badge: "Credits",
    category: ["token", "global", "aggregator"],
    quotaStyle: "Dollar credits · bonus up to 50%",
    tools: ["Kilo IDE", "CLI", "Cloud Agents", "KiloClaw", "Kilo Gateway", "OpenClaw / Hermes"],
    models: ["Claude", "GPT", "Gemini", "500+ models", "Auto Model routing"],
    highlights: [
      "Pay $X → ~$X credits + free bonus credits",
      "No markup vs provider list prices",
      "Marketplace for partner coding plans (e.g. MiniMax)",
      "Annual billing unlocks higher bonus",
    ],
    url: "https://kilo.ai/pricing/kilo-pass",
    docsUrl: "https://kilo.ai/pricing/kilo-pass",
    color: "#0F766E",
    tiers: [
      {
        name: "Starter",
        price: "$19",
        period: "/mo",
        alt: "Up to ~$26.60 credit value",
        quota: "Paid credits + welcome/streak bonus",
        note: "Light power users",
      },
      {
        name: "Pro",
        price: "$49",
        period: "/mo",
        alt: "Up to ~$68.60 credit value",
        quota: "Paid credits + bonus",
        note: "Daily AI coding",
        popular: true,
      },
      {
        name: "Expert",
        price: "$199",
        period: "/mo",
        alt: "Up to ~$278.60 credit value",
        quota: "Paid credits + bonus",
        note: "Heavy multi-product use",
      },
    ],
  },
  {
    id: "freebuff",
    name: "Freebuff",
    vendor: "Freebuff",
    tagline: "100% free coding agent (CLI, desktop, web, cloud, chat) powered by open models and ads.",
    startingPrice: 0,
    currency: "USD",
    priceLabel: "Free ($0)",
    railUnit: "",
    badge: "Free",
    category: ["open", "global", "agent", "free"],
    quotaStyle: "Free daily / limited mode",
    tools: ["Freebuff CLI", "Desktop", "Web", "Cloud", "Chat"],
    models: ["DeepSeek V4", "Kimi K2.7 Code", "MiniMax M3", "other open models"],
    highlights: [
      "No subscription and no API key required",
      "Positions as free alternative to Cursor / Claude Code / Devin class tools",
      "Supported by text ads",
      "Great for trying agent workflows at $0",
    ],
    url: "https://freebuff.com/",
    docsUrl: "https://freebuff.com/",
    color: "#16A34A",
    tiers: [
      {
        name: "Free",
        price: "$0",
        period: "",
        quota: "Daily free model access · limits apply",
        note: "npm i -g freebuff",
        popular: true,
      },
    ],
  },
  {
    id: "qoder",
    name: "Qoder",
    vendor: "Qoder",
    tagline: "Agentic coding platform with credit-based Pro / Pro+ / Ultra plans across desktop, CLI, and cloud agents.",
    startingPrice: 20,
    currency: "USD",
    priceLabel: "from $20/mo",
    badge: "Agent IDE",
    category: ["ide", "global", "agent"],
    quotaStyle: "Credits ≈ plan fee value / month",
    tools: ["Qoder Desktop", "CLI", "JetBrains", "Cloud Agents", "QoderWork", "Mobile"],
    models: ["Qwen3.7", "GLM-5.2", "premium models", "off-peak credit discounts"],
    highlights: [
      "Pro $20 · Pro+ $60 · Ultra $200",
      "Credits reset each subscription period",
      "Time-of-day credit multipliers on select models",
      "Teams from $40/seat/mo",
    ],
    url: "https://qoder.com",
    docsUrl: "https://docs.qoder.com/account/pricing",
    color: "#EA580C",
    tiers: [
      {
        name: "Pro",
        price: "$20",
        period: "/mo",
        alt: "~2,000 credits class",
        quota: "Day-to-day completion + light agent",
        note: "Most individuals",
        popular: true,
      },
      {
        name: "Pro+",
        price: "$60",
        period: "/mo",
        alt: "~6,000 credits class",
        quota: "Heavier autonomous agent use",
        note: "Power agent workflows",
      },
      {
        name: "Ultra",
        price: "$200",
        period: "/mo",
        alt: "~20,000 credits class",
        quota: "Long-running Quest-style tasks",
        note: "Maximum individual tier",
      },
      {
        name: "Teams",
        price: "$40",
        period: "/seat/mo",
        quota: "~3,000 credits / seat / mo",
        note: "Org seats + shared add-ons",
      },
    ],
  },
  {
    id: "cline",
    name: "ClinePass",
    vendor: "Cline",
    tagline: "Low-cost open-weight model subscription inside Cline IDE/CLI — no separate provider keys required.",
    startingPrice: 5,
    currency: "USD",
    priceLabel: "from $4.99 → $9.99/mo",
    badge: "Pass",
    category: ["token", "global", "agent", "aggregator", "open"],
    quotaStyle: "Monthly open-weight quota",
    tools: ["Cline IDE", "Cline CLI", "Other agents via API key"],
    models: [
      "GLM 5.2",
      "Kimi K3 / K2.7 Code / K2.6",
      "DeepSeek V4 Pro / Flash",
      "MiniMax M3",
      "MiMo V2.5 Pro / V2.5",
      "Qwen3.7-Max / Plus",
    ],
    highlights: [
      "Promo: $4.99 first month, then $9.99/mo",
      "Curated open weights from Z.ai, Moonshot, DeepSeek, MiniMax, MiMo, Qwen",
      "BYOK / other Cline providers still available",
      "Quotas positioned ~2–5× typical API rate limits",
    ],
    url: "https://cline.bot/cline-pass",
    docsUrl: "https://cline.bot/get-cline",
    color: "#0EA5E9",
    tiers: [
      {
        name: "ClinePass",
        price: "$9.99",
        period: "/mo",
        alt: "$4.99 first month (promo)",
        quota: "Open-weight models · generous quota",
        note: "No separate API keys",
        popular: true,
      },
      {
        name: "BYOK",
        price: "$0",
        period: "",
        quota: "Your own keys / providers",
        note: "Extension remains free",
      },
    ],
  },
  {
    id: "devin",
    name: "Devin",
    vendor: "Cognition",
    tagline: "Autonomous software engineer agent with plan quota plus on-demand credits.",
    startingPrice: 20,
    currency: "USD",
    priceLabel: "from $20/mo",
    badge: "Autonomous",
    category: ["agent", "global", "ide"],
    quotaStyle: "Plan quota + on-demand credits",
    tools: ["app.devin.ai", "Devin Review", "Integrations"],
    models: ["Devin agent stack"],
    highlights: [
      "Pro $20 · Max $200 individual seats",
      "Teams from $80/mo minimum + $40/full seat",
      "Idle sessions sleep (little/no usage burn)",
      "Enterprise still ACU-contracted",
    ],
    url: "https://devin.ai/pricing",
    docsUrl: "https://docs.devin.ai/admin/billing/self-serve",
    color: "#111827",
    tiers: [
      {
        name: "Free",
        price: "$0",
        period: "",
        quota: "Light quota · limited models",
        note: "Try Devin",
      },
      {
        name: "Pro",
        price: "$20",
        period: "/mo",
        quota: "Increased quota · on-demand credits",
        note: "Individual developers",
        popular: true,
      },
      {
        name: "Max",
        price: "$200",
        period: "/mo",
        quota: "Much larger weekly quota",
        note: "Near-continuous workloads",
      },
      {
        name: "Teams",
        price: "$80+",
        period: "/mo",
        alt: "$40 / full seat",
        quota: "Shared on-demand credits",
        note: "Multi-member workspaces",
      },
    ],
  },
  {
    id: "commandcode",
    name: "Command Code",
    vendor: "Command Code AI",
    tagline: "Flat monthly credit subscriptions with open-model deals and zero markup top-ups.",
    startingPrice: 1,
    currency: "USD",
    priceLabel: "from $1/mo",
    badge: "Credits",
    category: ["token", "global", "aggregator"],
    quotaStyle: "Included model credits + top-ups",
    tools: ["Command Code agent / tooling"],
    models: ["DeepSeek V4", "Qwen3.7", "MiniMax", "frontier models on higher tiers"],
    highlights: [
      "Go $1 · Pro $15 · Max 10× $100 · Max 20× $200",
      "Claims better-than-API effective rates via deals",
      "Top-up credits never expire · zero markup",
      "Team / Enterprise credit pools",
    ],
    url: "https://commandcode.ai/pricing",
    docsUrl: "https://commandcode.ai/pricing",
    color: "#DB2777",
    tiers: [
      {
        name: "Go",
        price: "$1",
        period: "/mo",
        alt: "~$10 credits included",
        quota: "Open-source model budgets",
        note: "Tiny entry tier",
      },
      {
        name: "Pro",
        price: "$15",
        period: "/mo",
        alt: "~$30 credits included",
        quota: "Side projects & weekend builds",
        note: "Popular light paid tier",
        popular: true,
      },
      {
        name: "Max 10×",
        price: "$100",
        period: "/mo",
        alt: "~$150 credits included",
        quota: "Daily shipping capacity",
        note: "Power users",
      },
      {
        name: "Max 20×",
        price: "$200",
        period: "/mo",
        quota: "Highest consumer credits",
        note: "All-out usage",
      },
    ],
  },
  {
    id: "verdent",
    name: "Verdent",
    vendor: "Verdent AI",
    tagline: "Credit-based coding assistant for VS Code and desktop with Eco Mode for low-cost models.",
    startingPrice: 5,
    currency: "USD",
    priceLabel: "from $5/mo",
    badge: "Credits",
    category: ["ide", "global", "agent"],
    quotaStyle: "Monthly credits · Eco Mode",
    tools: ["Verdent for VS Code", "Verdent Desktop"],
    models: ["Claude", "GPT", "Gemini", "GLM", "Kimi", "MiniMax", "DeepSeek"],
    highlights: [
      "Lite $5 · Starter $19 · Pro $59 · Max $179",
      "1 credit ≈ $0.059 · no markup on model cost",
      "Eco Mode continues on cheap models without credits",
      "BYOK / BYOA supported on free trial path",
    ],
    url: "https://www.verdent.ai/pricing",
    docsUrl: "https://www.verdent.ai/pricing",
    color: "#059669",
    tiers: [
      {
        name: "Lite",
        price: "$5",
        period: "/mo",
        quota: "Eco Mode + add credits",
        note: "Light experiments",
      },
      {
        name: "Starter",
        price: "$19",
        period: "/mo",
        alt: "Bonus credits often included",
        quota: "~480 credits / mo (w/ bonus)",
        note: "Occasional agent work",
        popular: true,
      },
      {
        name: "Pro",
        price: "$59",
        period: "/mo",
        alt: "Bonus credits often included",
        quota: "~1,500 credits / mo (w/ bonus)",
        note: "Regular daily use",
      },
      {
        name: "Max",
        price: "$179",
        period: "/mo",
        alt: "Bonus credits often included",
        quota: "~4,500 credits / mo (w/ bonus)",
        note: "Intensive workflows",
      },
    ],
  },
  {
    id: "kiro",
    name: "Amazon Kiro",
    vendor: "Amazon Web Services",
    tagline: "AWS agentic IDE / CLI with credit tiers from Free through Power.",
    startingPrice: 0,
    currency: "USD",
    priceLabel: "from Free / $20",
    badge: "AWS IDE",
    category: ["ide", "global", "agent"],
    quotaStyle: "Monthly credits · $0.04 add-ons",
    tools: ["Kiro IDE", "Kiro CLI", "Kiro Web", "ACP IDEs"],
    models: ["Auto", "Claude Sonnet / Opus", "Qwen", "DeepSeek", "MiniMax"],
    highlights: [
      "Free 50 credits · Pro 1k · Pro+ 2k · Pro Max 5k · Power 10k",
      "$20 first-upgrade credit with social / Builder ID",
      "Add-on credits $0.04 each (individuals)",
      "Not for third-party harnesses like OpenClaw",
    ],
    url: "https://kiro.dev/pricing",
    docsUrl: "https://kiro.dev/pricing",
    color: "#FF9900",
    tiers: [
      {
        name: "Free",
        price: "$0",
        period: "",
        quota: "50 credits / mo",
        note: "Open-weight + limited Claude",
      },
      {
        name: "Pro",
        price: "$20",
        period: "/mo",
        quota: "1,000 credits",
        note: "Premium models + add-ons",
        popular: true,
      },
      {
        name: "Pro+",
        price: "$40",
        period: "/mo",
        quota: "2,000 credits",
        note: "Heavier agent / spec work",
      },
      {
        name: "Pro Max",
        price: "$100",
        period: "/mo",
        quota: "5,000 credits",
        note: "Power individuals",
      },
      {
        name: "Power",
        price: "$200",
        period: "/mo",
        quota: "10,000 credits",
        note: "Maximum individual tier",
      },
    ],
  },
  {
    id: "trae",
    name: "Trae",
    vendor: "ByteDance",
    tagline: "AI-native IDE with SOLO agent mode, unlimited autocomplete on paid tiers, and Basic + Bonus usage balances.",
    startingPrice: 0,
    currency: "USD",
    priceLabel: "from Free / $3",
    badge: "IDE",
    category: ["ide", "global", "agent", "free", "china"],
    quotaStyle: "Basic + Bonus usage ($)",
    tools: ["Trae IDE", "SOLO Web", "SOLO Desktop"],
    models: ["Claude", "GPT", "Gemini", "DeepSeek", "Custom models"],
    highlights: [
      "Permanent Free tier · Lite $3 · Pro $10 after 7-day trial",
      "Token-based Basic Usage + Bonus subsidy (not flat requests)",
      "SOLO agent mode included on Pro and above",
      "ByteDance product · confirm live quotas on trae.ai",
    ],
    url: "https://www.trae.ai/pricing",
    docsUrl: "https://docs.trae.ai",
    color: "#0D9488",
    tiers: [
      {
        name: "Free",
        price: "$0",
        period: "",
        quota: "Limited usage · ~5k autocomplete / mo",
        note: "Standard queue · light SOLO",
      },
      {
        name: "Lite",
        price: "$3",
        period: "/mo",
        quota: "$5 Basic + Bonus usage",
        note: "Hobby / light edits",
      },
      {
        name: "Pro",
        price: "$10",
        period: "/mo",
        alt: "7-day free trial",
        quota: "$20 Basic + Bonus · unlimited autocomplete",
        note: "SOLO included · ~10 cloud tasks",
        popular: true,
      },
      {
        name: "Pro+",
        price: "$30",
        period: "/mo",
        quota: "~3.5× Pro usage",
        note: "Heavier agent sessions",
      },
      {
        name: "Ultra",
        price: "$100",
        period: "/mo",
        quota: "~20× Pro usage · early models",
        note: "Power users",
      },
    ],
  },
  {
    id: "ollama",
    name: "Ollama Cloud",
    vendor: "Ollama",
    tagline: "Local models stay free forever; Cloud adds hosted open models billed by GPU usage, not tokens.",
    startingPrice: 0,
    currency: "USD",
    priceLabel: "from Free / $20",
    badge: "Open models",
    category: ["open", "global", "free", "token", "agent"],
    quotaStyle: "GPU usage · 5h / 7d resets",
    tools: ["Ollama CLI", "Desktop apps", "API", "Community integrations"],
    models: ["Open cloud models", "Private model upload (Pro+)", "Local unlimited"],
    highlights: [
      "Local inference always unlimited and free",
      "Pro $20/mo · 50× Free cloud usage · 3 concurrent models",
      "Max $100/mo · 5× Pro · 10 concurrent (new Max paused)",
      "Usage = GPU time, not fixed token caps",
    ],
    url: "https://ollama.com/pricing",
    docsUrl: "https://docs.ollama.com",
    color: "#111827",
    tiers: [
      {
        name: "Free",
        price: "$0",
        period: "",
        quota: "Light cloud · 1 concurrent model",
        note: "Local unlimited · public models",
      },
      {
        name: "Pro",
        price: "$20",
        period: "/mo",
        alt: "$200/yr",
        quota: "50× Free cloud · 3 concurrent",
        note: "Larger models · private upload",
        popular: true,
      },
      {
        name: "Max",
        price: "$100",
        period: "/mo",
        quota: "5× Pro · 10 concurrent",
        note: "New sign-ups paused (capacity)",
      },
      {
        name: "Team",
        price: "Soon",
        period: "",
        quota: "Shared usage · SSO · admin",
        note: "Coming soon",
      },
    ],
  },
  {
    id: "nous",
    name: "Nous Portal",
    vendor: "Nous Research",
    tagline: "Unified gateway for Hermes Agent — 200+ models, hosted tools, and monthly credits with 10% bonus.",
    startingPrice: 0,
    currency: "USD",
    priceLabel: "from Free / $20",
    badge: "Hermes",
    category: ["token", "global", "aggregator", "agent", "free"],
    quotaStyle: "Monthly credits · rollover caps",
    tools: ["Hermes Agent", "Hermes Desktop", "Nous Chat", "OpenAI-compatible API", "Hermes Cloud"],
    models: ["Claude", "GPT", "Gemini", "DeepSeek", "Qwen", "Kimi", "GLM", "MiniMax", "Grok", "Hermes 4", "200+"],
    highlights: [
      "Official backend for Hermes Agent (one OAuth login)",
      "Paid tiers: pay $X → $X+10% monthly credits",
      "Hosted tools: search, image, TTS, browser, code sandbox",
      "Optional Hermes Cloud instances billed from credits",
    ],
    url: "https://portal.nousresearch.com/manage-subscription",
    docsUrl: "https://hermes-agent.nousresearch.com/docs/integrations/nous-portal",
    color: "#7C2D12",
    tiers: [
      {
        name: "Free",
        price: "$0",
        period: "/mo",
        quota: "Free models · $0 monthly credits",
        note: "Evaluation / light tryouts",
      },
      {
        name: "Plus",
        price: "$20",
        period: "/mo",
        alt: "$22 credits · $10 rollover cap",
        quota: "200+ models · hosted tools · high limits",
        note: "Recommended for Hermes Agent",
        popular: true,
      },
      {
        name: "Super",
        price: "$100",
        period: "/mo",
        alt: "$110 credits · $50 rollover cap",
        quota: "200+ models · hosted tools · high limits",
        note: "Heavier agent + tool usage",
      },
      {
        name: "Ultra",
        price: "$200",
        period: "/mo",
        alt: "$220 credits · $100 rollover cap",
        quota: "200+ models · hosted tools · highest limits",
        note: "Maximum Portal tier",
      },
    ],
  },
];

window.FILTERS = [
  { id: "all", label: "All plans" },
  { id: "token", label: "Token packs" },
  { id: "aggregator", label: "Multi-model" },
  { id: "official", label: "Frontier labs" },
  { id: "china", label: "China-native" },
  { id: "global", label: "Global" },
  { id: "mcp", label: "MCP extras" },
  { id: "ide", label: "IDE suites" },
  { id: "agent", label: "Agent-heavy" },
  { id: "open", label: "Open / BYOK" },
  { id: "free", label: "Free entry" },
];
